### ISSUE TITLE
Change set-env to non-disabled command

### ISSUE THREAD

**Issue by infamousjoeg** [infamousjoeg/conjur-action#4]
The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by quincycheng** [comment]
Hi @infamousjoeg, may I know if it's fixed & released?
`ACTIONS_ALLOW_UNSECURE_COMMANDS: true` is required at this moment which is not ideal. 
Thanks.
